### ISSUE TITLE
USER STORY: Favourites

### ISSUE THREAD

**Issue by AMartins87** [AMartins87/games_exclusives#23]
As a **Registered Shopper** I can **add or remove a game to my favourites** so that **I can either purchase it again or go back to it at later stage without prolonged searches**.

---

**ACCEPTANCE CRITERIA**

- **When** I click the heart icon or link **Then** the game is added to my favourites list.

**TASKS**

- [x]  Create favourites view  in profiles views
- [x]  Create favourites html template
- [x]  Create favourites model in profiles app
- [x]  Add code to games and game detail html template page
- [x]  Create add to favourites view in profiles views
- [x]  Create remove from favourites view in profile views
- [x]  Add to URLs
