### ISSUE TITLE
USER STORY: Shopping Basket - Add/Remove Products

### ISSUE THREAD

**Issue by AMartins87** [AMartins87/games_exclusives#7]
As a **Shopper** I can **add or remove products in the shopping basket** so that I can **buy the wanted amount if I change my mind**.

---

**ACCEPTANCE CRITERIA**
- **When** I click on the plus or minus buttons **Then** the quantity of games is adjusted
- **When** I remove a game from my basket **Then** the game is removed

**TASKS**

- [x]  Create adjust basket view
- [x]  Create remove from basket view
- [x]  Add html to basket.html template
- [x]  Add to URLs
